from enum import IntFlag


class HyundaiSafetyFlagsIQ:
  DEFAULT = 0
  ESCC = 1
  LONG_MAIN_CRUISE_TOGGLEABLE = 2
  HAS_LDA_BUTTON = 4
  NON_SCC = 8


class HyundaiFlagsIQ(IntFlag):
  ENHANCED_SCC = 1
  HAS_LFA_BUTTON = 2
  LONGITUDINAL_MAIN_CRUISE_TOGGLEABLE = 2 ** 2
  ENABLE_RADAR_TRACKS_DEPRECATED = 2 ** 3
  LONG_TUNING_DYNAMIC = 2 ** 4
  LONG_TUNING_PREDICTIVE = 2 ** 5
  NON_SCC = 2 ** 6
  NON_SCC_RADAR_FCA = 2 ** 7
  NON_SCC_NO_FCA = 2 ** 8
  SPEED_LIMIT_AVAILABLE = 2 ** 9
  HAS_LKAS12 = 2 ** 10


